### ISSUE TITLE
Fatal v8 error in Node LTS 6.9.2 / 6.10.2

### ISSUE THREAD

**Issue by tristanhoy** [cyph/sphincs.js#1]
This is more of a note than an issue - but on Windows in Nodejs 6.9.2 (V8 5.1.281) the third line in the following script causes an error in the [v8 compiler](https://github.com/nodejs/node/blob/v6.x/deps/v8/src/compiler.cc#L786):
```js
const sphincs = require('sphincs')
console.log('blah')
const keyPair = sphincs.keyPair()
```
```
blah


#
# Fatal error in ..\..\src\compiler.cc, line 786
# Check failed: !info->shared_info()->feedback_vector()->metadata()->SpecDiffersFrom( info->literal()->feedback_vector_spec()).
#
```
Node 7.8.0 (V8 5.5.372) is not affected - so the resolution is to either switch to latest or wait for Node LTS 8.x.x.

I haven't tested on Linux but I have no reason to believe this is specific to Windows as it's precompiled javascript and not a node-gyp, python or C++ dist issue.

**Comment by buu700** [comment]
Thanks for reporting this! I was able to reproduce the problem in Node 6.10.2 on Linux; glad to know that 7.8 fixes it. Not sure there's much I can do about this on my end though.

I would open issues with Node and V8 to see if at least one of them can backport the change(s) that resolved this to the Node LTS and/or whatever version of V8 it uses.

**Comment by tristanhoy** [comment]
So it turns out the debug compile isn't affected - the following works just fine in 6.10.2:

```js
const sphincs = require('./node_modules/sphincs/dist/sphincs.debug.js')
const keyPair = sphincs.keyPair()
```

You could potentially add a "sphincs.legacy.js" compile that has less aggressive optimisations and no debugging? This would take just a few minutes to find an optimisation level that works.

As I'm on a Windows machine things like getting EMCC to work aren't worth the trouble (tried for half a day previously and gave up), otherwise I'd do this myself and submit a pull.

**Comment by tristanhoy** [comment]
Issue logged with Node https://github.com/nodejs/node/issues/12308.

Issues are turned off for the V8 repo.
